# Custom broker properties for ZooKeeper-based cluster

# Listener configuration
listener.security.protocol.map=INTERBROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
inter.broker.listener.name=INTERBROKER

# Kafka default: true
auto.create.topics.enable=false

# Replication settings
default.replication.factor=3
min.insync.replicas=2

# Log and partition settings
# kafka default -1
log.retention.bytes=100000000
# kafka default 1GiB
log.segment.bytes=20000000
