# Custom broker properties for ZooKeeper-based cluster

# Listener configuration
listener.security.protocol.map=INTERBROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
inter.broker.listener.name=INTERBROKER

# Kafka default: true
auto.create.topics.enable=false

# Replication settings
default.replication.factor=3
min.insync.replicas=2

# Log and partition settings
# kafka default -1
log.retention.bytes=100000000
# kafka default 1GiB
log.segment.bytes=20000000


# num.partitions=3
# num.recovery.threads.per.data.dir=1
# log.retention.hours=168
# log.segment.bytes=1073741824
# log.retention.check.interval.ms=300000

# offsets.topic.replication.factor=3
# transaction.state.log.replication.factor=3
# transaction.state.log.min.isr=2

# Thread and socket settings
# num.network.threads=3
# num.io.threads=8
# socket.send.buffer.bytes=102400
# socket.receive.buffer.bytes=102400
# socket.request.max.bytes=104857600

