# Custom controller properties for KRaft cluster

# Listener configuration
controller.listener.names=CONTROLLER

# Kafka default: true
auto.create.topics.enable=false

# Cluster-wide replication defaults (KRaft mode)
# These settings are applied by controllers to all newly created topics
default.replication.factor=3
min.insync.replicas=2

# Log and partition settings
# kafka default -1
log.retention.bytes=100000000
# kafka default 1GiB
log.segment.bytes=20000000

