# override to the configs/server.properties used inside the kafka*.tgz
#
# Kafka default: true
auto.create.topics.enable=false
# Kafka default: 1
default.replication.factor=3
# Kafka default: 1
min.insync.replicas=2
